name: favorite_place_medium
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  uuid: ^4.4.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  location: ^7.0.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
